### ISSUE TITLE
Wierd looking font when using |=

### ISSUE THREAD

**Issue by Kaaserne** [somq/consolas-ligaturized#4] opened 2020-01-08 13:46 UTC
Somewhere in my code I'm using for e.g.
```cpp
someVal |= someOtherVal
someVal &= someOtherVal
```

However, `|=` looks kind of weird while `&=` and for e.g. `a | b` looks like its normal Consolas font.
Is this 'ligutarization' supposed to be this way?

 ![](https://i.imgur.com/FoINV38.png)

**Comment by somq** [comment] 2020-01-08 13:53
Does it look the same using [FiraCode](https://github.com/tonsky/FiraCode/wiki) standard font?  
I guess that yes because I can see this ligature (|=) in their [demo screenshot](https://github.com/tonsky/FiraCode#solution)  

---
See down-right corner  

![firacode demo](https://raw.githubusercontent.com/tonsky/FiraCode/master/showcases/all_ligatures.png)

**Comment by Kaaserne** [comment] 2020-01-08 16:02
Hmm that's weird, cause my IDE says Consolas Ligaturized is enabled:

![](https://i.imgur.com/aYWx8MT.png)

Any ideas?

**Comment by somq** [comment] 2020-01-08 17:02
I don't think `a | b` or `&=` has any ligatures.  
Can you reproduce what's on the demo image above? Does the special arrows works for instance?

**Comment by Kaaserne** [comment] 2020-01-09 08:07
File -> settings -> Editor -> Font.
- Font: Consolas Ligaturized
- Fallback font <None>
- Check enable font ligatures

Editor -> Color Scheme -> Color Scheme Font:
- Unchecked "Use color scheme font instead of the default (Consolas Ligaturized, 13)

Editor -> Color Scheme -> Console Font:
- Same settings as described above.

Some samples:

![](https://i.imgur.com/8BOMOIa.png)

The `&& || -> <-` etc, look very much like the Fira Code Retina, however the normal font, as in the letters itself, looks like Consolas.

**Comment by somq** [comment] 2020-01-09 15:18
Do you mean that ligaturized characters are not made out of legacy consolas characters?  
If yes, this is unfortuantely the way `ligaturizer` works.   

> This script copies the ligatures (glyphs and rendering information) from Fira Code into any other TrueType or OpenType font.  

ref: https://github.com/ToxicFrog/Ligaturizer#ligaturizer

**Comment by Kaaserne** [comment] 2020-01-10 10:28
Ah my bad. I thought this font customized those ligaturizations aswell.

**Comment by somq** [comment] 2020-01-10 10:49
No prob, If you have any alternative solution to provide legacy consolas characters ligatures feel free to open a new issue or make a PR.
I'm closing this one for now.

**Closed as completed by somq** 2020-01-10 10:49 UTC
